backend:
  name: github
  repo: sdzaveri/capital-website-netlify

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: "navigation"
    label: "Navigation"
    extension: "json"
    format: "json"
    folder: src/data/navigation
    editor:
       preview: false
    fields:
      - name: sections
        label: Sections
        widget: list
        fields:
        - {name: title}
        - name: links
          label: Links
          widget: list
          fields:
            - {name: title}
            - {name: url}
  - name: overview
    label: Overview
    folder: src/pages/overview
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
  - name: styles
    label: Styles
    folder: src/pages/styles
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
  - name: patterns
    label: Patterns
    folder: src/pages/patterns
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
  - name: components
    label: Components
    folder: src/pages/components
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
  - name: guidelines
    label: Guidelines
    folder: src/pages/guidelines
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
