backend:
  name: github
  repo: sdzaveri/capital-website-netlify

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: patterns
    label: Patterns
    folder: src/pages/patterns
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
  - name: "navigation"
    label: "Navigation"
    files:
      - file: "src/data/navigation.json"
        label: "Navigation"
        name: "navigation"
        extension: "json"
        format: "json"
        editor:
           preview: false
        fields:
          - { name: body, label: Body, widget: code }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/overview/principles.mdx"
        label: "Principles"
        name: "principles"
        extension: mdx
        format: frontmatter
        fields:
          - { name: title, label: Title }
          - { name: description, label: Description }
          - { name: activeTab, label: Active Tab }
          - { name: body, label: Body, widget: markdown }
      - file: "src/pages/overview/contribution-developers.md"
        label: "Developer Contribution Guidelines"
        name: "devcontributionguidelines"
        fields:
          - { name: title, label: Title }
          - { name: description, label: Description }
          - { name: activeTab, label: Active Tab }
          - { name: body, label: Body, widget: markdown }
