backend:
  name: github
  repo: sdzaveri/capital-website-netlify

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: "navigation"
    label: "Navigation"
    extension: "json"
    format: "json"
    folder: src/data/navigation
    slug: "{{slug}}"
    editor:
       preview: false
    fields:
      - name: sections
        label: Sections
        widget: list
        fields:
        - {name: title}
        - name: links
          label: Links
          widget: list
          fields:
            - {name: title}
            - {name: url}
  - name: "glossary"
    label: "Glossary"
    extension: "json"
    format: "json"
    folder: src/data/glossary
    slug: "{{slug}}"
    editor:
       preview: false
    fields:
      - name: terms
        label: Terms
        widget: list
        fields:
        - name: term
          label: Terms
          widget: list
          fields:
            - {name: component}
            - {name: term}
            - {name: definition}
            - {name: term}
            - {label: Tags, name: tags, widget: list }
            - {label: Related Terms, name: relatedTerms, widget: list }
            - label: "Related Links"
              name: "relatedLinks"
              collapsed: false
              widget: "list"
              fields:
                - {label: URL, name: url, widget: string, default: "/"}
                - {label: Name, name: name, widget: string }
  - name: overview
    label: Overview
    folder: src/pages/overview
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
  - name: styles
    label: Styles
    folder: src/pages/styles
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
  - name: patterns
    label: Patterns
    folder: src/pages/patterns
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
  - name: components
    label: Components
    folder: src/pages/components
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: activeTab, label: Active Tab }
      - { name: body, label: Body, widget: markdown }
